route:
  receiver: slack

receivers:
  - name: slack
    slack_configs:
      - api_url: "https://hooks.slack.com/services/..."
        text: "{{ .CommonAnnotations.summary }} - {{ .CommonAnnotations.description }}"
        channel: 'alert-prom'
        send_resolved: true
