route:
  receiver: slack

receivers:
  - name: slack
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        text: "{{ .CommonAnnotations.summary }} - {{ .CommonAnnotations.description }}"